create or replace FUNCTION HCD_OBTER_INTERVENCOES_SAE( NR_SEQUENCIA_P	NUMBER)
 		    	RETURN VARCHAR2 IS

QUEBRA_W		VARCHAR2(10) := CHR(13)||CHR(10);
DS_RETORNO_W		VARCHAR2(4000);
DS_PROCEDIMENTO_W	VARCHAR2(4000);


CURSOR C01 IS
SELECT 	DS_PROCEDIMENTO
FROM   	PE_PRESCR_PROC A,
	PE_PROCEDIMENTO B
WHERE  1=1
AND	A.NR_SEQ_PROC = B.NR_SEQUENCIA
AND	A.NR_SEQ_PRESCR = NR_SEQUENCIA_P
order by ds_procedimento;


BEGIN

OPEN C01;
LOOP
FETCH C01 INTO
	DS_PROCEDIMENTO_W;
EXIT WHEN C01%NOTFOUND;
	BEGIN
	BEGIN
	IF (DS_RETORNO_W IS NULL) THEN
		DS_RETORNO_W:= DS_PROCEDIMENTO_W;
	ELSE
		DS_RETORNO_W := DS_RETORNO_W || QUEBRA_W ||DS_PROCEDIMENTO_W;
	END IF;
	EXCEPTION
	WHEN OTHERS THEN
		DS_RETORNO_W	:= DS_RETORNO_W|| SUBSTR(DS_PROCEDIMENTO_W,4,3000||QUEBRA_W||DS_RETORNO_W);
	END;
	END;
END LOOP;
CLOSE C01;

RETURN 	SUBSTR(DS_RETORNO_W,1,3000);

END HCD_OBTER_INTERVENCOES_SAE;