CREATE OR REPLACE FUNCTION HCD_OBTER_PRIMEIRA_SAE_CONFORM (NR_ATENDIMENTO_P NUMBER, DT_ENTRADA_P DATE)
RETURN VARCHAR2 IS

/*<DS_SCRIPT>
 DESCRIÇÃO...: FUNCTION QUE RETORNA SE A PRIMEIRA SAE FOI REALIZADA ATÉ 3 HORAS APÓS A ENTRADA DO PACIENTE
 RESPONSAVEL.: ARTUR VINICIUS (ARTUR.VINICIUS)
 DATA........: 17/11/2022
 APLICAÇÃO...: TASY
 ATUALIZAÇÃO...:
</DS_SCRIPT>*/

DS_RETORNO_W VARCHAR2(50);
IE_RETORNA_VALOR NUMBER;


BEGIN
    SELECT MIN(B.NR_SEQUENCIA)
            INTO IE_RETORNA_VALOR
            FROM PE_PRESCRICAO B 
            WHERE B.NR_ATENDIMENTO = NR_ATENDIMENTO_P
            AND B.DT_PRESCRICAO BETWEEN (DT_ENTRADA_P) AND (DT_ENTRADA_P +3/24);
            
    IF (IE_RETORNA_VALOR IS NOT NULL)
    THEN DS_RETORNO_W := 'SIM';
    ELSE DS_RETORNO_W := 'NAO';
    END IF;
    
RETURN DS_RETORNO_W;
END HCD_OBTER_PRIMEIRA_SAE_CONFORM;