CREATE OR REPLACE TRIGGER HCD_BLOQ_INI_CIR_ATEND
BEFORE UPDATE ON CIRURGIA
FOR EACH ROW
WHEN (NEW.DT_ENTRADA_UNIDADE IS NOT NULL AND NEW.DT_INICIO_REAL IS NOT NULL)

/*<DS_SCRIPT>
 DESCRIÇÃO...: TRIGGER QUER REALIZA O BLOQUEIO CASO NO CAMPO INICIO REAL DA CIRURGIA SEJA INFORMADA UMA DATA MENOR QUE A DATA DO ATENDIMENTO
 RESPONSAVEL.: DOUGLAS FELIPE 
 DATA........: 23/02/2023
 APLICAÇÃO...: TASY - Prontuário Eletrônico do Paciente - PEP >> Cirurgias
 ATUALIZAÇÃO...:

</DS_SCRIPT>*/


DECLARE

NR_CIRURGIA_W NUMBER := :NEW.NR_CIRURGIA;
NR_ATENDIMENTO_W NUMBER := :NEW.NR_ATENDIMENTO;
DT_ENTRA_UNIDADE_W DATE := :NEW.DT_ENTRADA_UNIDADE;
DT_INICIO_REAL_W DATE := :NEW.DT_INICIO_REAL;



DT_ENTRADA_ATEND DATE;

BEGIN

    SELECT DT_ENTRADA
    INTO DT_ENTRADA_ATEND
    FROM ATENDIMENTO_PACIENTE 
    WHERE NR_ATENDIMENTO = NR_ATENDIMENTO_W;
    
    
    -- VERIFICA SE A DATA INFORMADA É MENOR QUE A DATA DE ENTRADA DO PACIENTE --
    IF(DT_ENTRADA_ATEND > DT_ENTRA_UNIDADE_W OR DT_ENTRADA_ATEND > DT_INICIO_REAL_W)
    THEN
       wheb_mensagem_pck.exibir_mensagem_abort('Não é possível iniciar a cirurgia com data inferior a de abertura do atendimento.');
    END IF;

END HCD_BLOQ_INI_CIR_ATEND;