create or replace TRIGGER HCD_TRG_GESTAO_VAGA_LOG
AFTER INSERT OR DELETE OR UPDATE  OF IE_STATUS,CD_TIPO_ACOMOD_DESEJ,CD_TIPO_ACOMOD_ATUAL,CD_SETOR_DESEJADO,CD_UNIDADE_BASICA ON GESTAO_VAGA
FOR EACH ROW

/*<DS_SCRIPT>
 DESCRIÇÃO...: Trigger que realiza a inserção na tabela HCD_GESTAO_VAGA_LOG com alguns dados da tabela GESTAO_VAGA
 RESPONSAVEL.: JOSE WESKLEY (jose.weskley)
 DATA........: 20/12/2022
 APLICAÇÃO...: TASY
 ATUALIZAÇÃO...:
    -- EXEMPLO:Atualizado em XX/XX/XXXX por jose.weskley: Adicionado...
 OBSERVAÇÕES...:  

</DS_SCRIPT>*/

DECLARE

isInsertorUpdateorDelete_w varchar2(10);

BEGIN

if (inserting) then
	isInsertorUpdateorDelete_w := 'INSERT';
elsif (updating) then
	isInsertorUpdateorDelete_w := 'UPDATE';
else
    isInsertorUpdateorDelete_w := 'DELETE';
end if;

INSERT INTO HCD_GESTAO_VAGA_LOG (NR_SEQ_LOG,NR_SEQUENCIA,DT_ATUALIZACAO,NM_USUARIO,CD_PESSOA_FISICA,NR_ATENDIMENTO,IDADE,CD_MEDICO,CD_CONVENIO,DS_STATUS,CD_SETOR_ATUAL,CD_TIPO_ACOMOD_ATUAL,CD_SETOR_DESEJADO,CD_TIPO_ACOMOD_DESEJ,CD_UNIDADE_BASICA,CD_UNIDADE_COMPL,
                                        DT_SOLICITACAO,IE_SOLICITACAO,DT_ULT_DATA_RESERVA,DS_ACAO) 
                        VALUES (HCD_GESTAO_VAGA_LOG_SEQ.NEXTVAL,:NEW.NR_SEQUENCIA,SYSDATE,nvl(wheb_usuario_pck.get_nm_usuario,'TASY'),:NEW.CD_PESSOA_FISICA,:NEW.NR_ATENDIMENTO,OBTER_DADOS_PF(:NEW.CD_PESSOA_FISICA,'I'),:NEW.CD_MEDICO,:NEW.CD_CONVENIO,obter_valor_dominio(1408, :NEW.IE_STATUS),:NEW.CD_SETOR_ATUAL,:NEW.CD_TIPO_ACOMOD_ATUAL,:NEW.CD_SETOR_DESEJADO,
                                        :NEW.CD_TIPO_ACOMOD_DESEJ,:NEW.CD_UNIDADE_BASICA,:NEW.CD_UNIDADE_COMPL,:NEW.DT_SOLICITACAO,:NEW.IE_SOLICITACAO,:NEW.DT_ULT_DATA_RESERVA,isInsertorUpdateorDelete_w);



END HCD_TRG_GESTAO_VAGA_LOG;