CREATE OR REPLACE TRIGGER HCD_BQ_PRECAUCAO_SEM_ANALISE
BEFORE UPDATE ON ATENDIMENTO_PRECAUCAO
FOR EACH ROW
WHEN (NEW.DT_TERMINO IS NOT NULL)

DECLARE

DT_ANALISE_W DATE := :NEW.DT_ANALISE;


BEGIN
    IF(DT_ANALISE_W IS NULL) THEN
        wheb_mensagem_pck.exibir_mensagem_abort(CHR(10) || 'Não é possível finalizar a precaução sem a análise informada!' || CHR(10) || CHR(10) || 'Trigger: HCD_BQ_PRECAUCAO_SEM_ANALISE');
    END IF;

END HCD_BQ_PRECAUCAO_SEM_ANALISE;