CREATE OR REPLACE TRIGGER HCD_TRG_GERA_RECOM_PRECAUCAO
AFTER UPDATE ON ATENDIMENTO_PRECAUCAO
FOR EACH ROW

/*<DS_SCRIPT>
 DESCRIÇÃO...: TRIGGER QUE GERA A PRESCRIÇÃO DE ITENS(RECOMENDAÇÃO) NA CPOE APARTIR DA LIBERAÇÃO DE UMA PRECAUÇÃO LANÇADA NA ABA CIH
 RESPONSAVEL.: DOUGLAS FELIPE 
 DATA........: 23/01/2022
 APLICAÇÃO...: TASY - Prontuário Eletrônico do Paciente - PEP --> CIH
 ATUALIZAÇÃO...:

</DS_SCRIPT>*/


DECLARE

NR_ATENDIMENTO_W NUMBER := :NEW.NR_ATENDIMENTO;
NR_SEQ_AP_W NUMBER := :NEW.NR_SEQUENCIA;
DT_LIBERACAO_W DATE := :NEW.DT_LIBERACAO;
DT_INATIVACAO_W DATE := :NEW.DT_INATIVACAO;
NR_SEQ_PRECAUCAO_W NUMBER := :NEW.NR_SEQ_PRECAUCAO;
CD_PESSOA_FISICA_W NUMBER := :NEW.CD_PESSOA_FISICA;

NR_SEQ_W CPOE_RECOMENDACAO.NR_SEQUENCIA%TYPE;


DT_ATT_W DATE := SYSDATE;


IE_VERIFICA_REC NUMBER := 0;

BEGIN
    IF(dt_liberacao_w IS NOT NULL AND NR_SEQ_AP_W IS NOT NULL AND DT_INATIVACAO_W IS NULL)
        THEN
            
            IF(nr_seq_precaucao_w = 6 AND IE_VERIFICA_REC = 0) -- Padrão
                THEN
                            
                            NR_SEQ_W := cpoe_recomendacao_seq.NEXTVAL;
                
                            INSERT INTO cpoe_recomendacao (
                            cd_funcao_origem,
                            ie_oncologia,
                            ie_urgencia,
                            qt_dias_padrao,
                            dt_inicio,
                            cd_recomendacao,
                            dt_liberacao,
                            nr_seq_pepo,
                            dt_lib_suspensao,
                            ie_nivel_atencao,
                            dt_prox_geracao,
                            ie_retrogrado,
                            dt_liberacao_enf,
                            ie_item_valido,
                            cd_medico,
                            nr_cirurgia,
                            ie_administracao,
                            dt_atualizacao_nrec,
                            nr_seq_transcricao,
                            ie_prescritor_aux,
                            nr_sequencia,
                            dt_liberacao_aux,
                            ie_futuro,
                            dt_liberacao_farm,
                            dt_ciencia_medico,
                            ie_acm,
                            ie_periodo,
                            ie_duracao,
                            nr_ocorrencia,
                            hr_prim_horario,
                            cd_pessoa_fisica,
                            nr_cirurgia_patologia,
                            cd_perfil_ativo,
                            ie_se_necessario,
                            ds_recomendacao,
                            dt_atualizacao,
                            cd_intervalo,
                            ie_item_alta,
                            nr_seq_topografia,
                            ie_evento_unico,
                            nr_seq_soap,
                            nm_usuario,
                            nr_seq_cpoe_anterior,
                            dt_fim,
                            nr_seq_agenda,
                            nr_atendimento,
                            ie_tipo_prescr_cirur,
                            ds_justificativa,
                            nr_seq_conclusao_apae,
                            nm_usuario_nrec,
                            ds_horarios,
                            cd_setor_atendimento
                        ) VALUES (
                            2314,
                           'N',
                            NULL,
                            NULL,
                            DT_LIBERACAO_W,
                            321,
                            NULL,
                            NULL,
                            NULL,
                            'T',
                            NULL,
                            'N',
                            NULL,
                            'S',
                            NULL,
                            NULL,
                            'P',
                            DT_ATT_W,
                            NULL,
                            NULL,
                            NR_SEQ_W,
                            NULL,
                            'N',
                            NULL,
                            NULL,
                            'N',
                            NULL,
                            'C',
                            1.0,
                            TO_CHAR(DT_ATT_W,'HH24:MI'),
                            CD_PESSOA_FISICA_W,
                            NULL,
                            NULL,
                            'S',
                            NULL,
                            DT_ATT_W,
                            'Cont',
                            'N',
                            NULL,
                            'N',
                            NULL,
                            obter_usuario_ativo(),
                            NULL,
                            NULL,
                            NULL,
                            nr_atendimento_w,
                            NULL,
                            NULL,
                            NULL,
                            obter_usuario_ativo(),
                            NULL,
                            NULL
                        );
                        
                        IE_VERIFICA_REC := IE_VERIFICA_REC + 1;
            END IF;
            
            IF(nr_seq_precaucao_w = 10 AND IE_VERIFICA_REC = 0) -- Imunosuprimidos
                THEN
                            
                            NR_SEQ_W := cpoe_recomendacao_seq.NEXTVAL;
                
                            INSERT INTO cpoe_recomendacao (
                            cd_funcao_origem,
                            ie_oncologia,
                            ie_urgencia,
                            qt_dias_padrao,
                            dt_inicio,
                            cd_recomendacao,
                            dt_liberacao,
                            nr_seq_pepo,
                            dt_lib_suspensao,
                            ie_nivel_atencao,
                            dt_prox_geracao,
                            ie_retrogrado,
                            dt_liberacao_enf,
                            ie_item_valido,
                            cd_medico,
                            nr_cirurgia,
                            ie_administracao,
                            dt_atualizacao_nrec,
                            nr_seq_transcricao,
                            ie_prescritor_aux,
                            nr_sequencia,
                            dt_liberacao_aux,
                            ie_futuro,
                            dt_liberacao_farm,
                            dt_ciencia_medico,
                            ie_acm,
                            ie_periodo,
                            ie_duracao,
                            nr_ocorrencia,
                            hr_prim_horario,
                            cd_pessoa_fisica,
                            nr_cirurgia_patologia,
                            cd_perfil_ativo,
                            ie_se_necessario,
                            ds_recomendacao,
                            dt_atualizacao,
                            cd_intervalo,
                            ie_item_alta,
                            nr_seq_topografia,
                            ie_evento_unico,
                            nr_seq_soap,
                            nm_usuario,
                            nr_seq_cpoe_anterior,
                            dt_fim,
                            nr_seq_agenda,
                            nr_atendimento,
                            ie_tipo_prescr_cirur,
                            ds_justificativa,
                            nr_seq_conclusao_apae,
                            nm_usuario_nrec,
                            ds_horarios,
                            cd_setor_atendimento
                        ) VALUES (
                            2314,
                           'N',
                            NULL,
                            NULL,
                            DT_LIBERACAO_W,
                            322,
                            NULL,
                            NULL,
                            NULL,
                            'T',
                            NULL,
                            'N',
                            NULL,
                            'S',
                            NULL,
                            NULL,
                            'P',
                            DT_ATT_W,
                            NULL,
                            NULL,
                            NR_SEQ_W,
                            NULL,
                            'N',
                            NULL,
                            NULL,
                            'N',
                            NULL,
                            'C',
                            1.0,
                            TO_CHAR(DT_ATT_W,'HH24:MI'),
                            CD_PESSOA_FISICA_W,
                            NULL,
                            NULL,
                            'S',
                            NULL,
                            DT_ATT_W,
                            'Cont',
                            'N',
                            NULL,
                            'N',
                            NULL,
                            obter_usuario_ativo(),
                            NULL,
                            NULL,
                            NULL,
                            nr_atendimento_w,
                            NULL,
                            NULL,
                            NULL,
                            obter_usuario_ativo(),
                            NULL,
                            NULL
                        );
                        
                        IE_VERIFICA_REC := IE_VERIFICA_REC + 1;
            END IF;
            
            IF(nr_seq_precaucao_w = 9 AND IE_VERIFICA_REC = 0) -- Contato
                THEN
                            
                            NR_SEQ_W := cpoe_recomendacao_seq.NEXTVAL;
                
                            INSERT INTO cpoe_recomendacao (
                            cd_funcao_origem,
                            ie_oncologia,
                            ie_urgencia,
                            qt_dias_padrao,
                            dt_inicio,
                            cd_recomendacao,
                            dt_liberacao,
                            nr_seq_pepo,
                            dt_lib_suspensao,
                            ie_nivel_atencao,
                            dt_prox_geracao,
                            ie_retrogrado,
                            dt_liberacao_enf,
                            ie_item_valido,
                            cd_medico,
                            nr_cirurgia,
                            ie_administracao,
                            dt_atualizacao_nrec,
                            nr_seq_transcricao,
                            ie_prescritor_aux,
                            nr_sequencia,
                            dt_liberacao_aux,
                            ie_futuro,
                            dt_liberacao_farm,
                            dt_ciencia_medico,
                            ie_acm,
                            ie_periodo,
                            ie_duracao,
                            nr_ocorrencia,
                            hr_prim_horario,
                            cd_pessoa_fisica,
                            nr_cirurgia_patologia,
                            cd_perfil_ativo,
                            ie_se_necessario,
                            ds_recomendacao,
                            dt_atualizacao,
                            cd_intervalo,
                            ie_item_alta,
                            nr_seq_topografia,
                            ie_evento_unico,
                            nr_seq_soap,
                            nm_usuario,
                            nr_seq_cpoe_anterior,
                            dt_fim,
                            nr_seq_agenda,
                            nr_atendimento,
                            ie_tipo_prescr_cirur,
                            ds_justificativa,
                            nr_seq_conclusao_apae,
                            nm_usuario_nrec,
                            ds_horarios,
                            cd_setor_atendimento
                        ) VALUES (
                            2314,
                           'N',
                            NULL,
                            NULL,
                            DT_LIBERACAO_W,
                            324,
                            NULL,
                            NULL,
                            NULL,
                            'T',
                            NULL,
                            'N',
                            NULL,
                            'S',
                            NULL,
                            NULL,
                            'P',
                            DT_ATT_W,
                            NULL,
                            NULL,
                            NR_SEQ_W,
                            NULL,
                            'N',
                            NULL,
                            NULL,
                            'N',
                            NULL,
                            'C',
                            1.0,
                            TO_CHAR(DT_ATT_W,'HH24:MI'),
                            CD_PESSOA_FISICA_W,
                            NULL,
                            NULL,
                            'S',
                            NULL,
                            DT_ATT_W,
                            'Cont',
                            'N',
                            NULL,
                            'N',
                            NULL,
                            obter_usuario_ativo(),
                            NULL,
                            NULL,
                            NULL,
                            nr_atendimento_w,
                            NULL,
                            NULL,
                            NULL,
                            obter_usuario_ativo(),
                            NULL,
                            NULL
                        );
                        
                        IE_VERIFICA_REC := IE_VERIFICA_REC + 1;
            END IF;
            
        IF(nr_seq_precaucao_w = 7 AND  IE_VERIFICA_REC = 0) -- Aerossóis
                THEN
                            NR_SEQ_W := cpoe_recomendacao_seq.NEXTVAL;
                
                            INSERT INTO cpoe_recomendacao (
                            cd_funcao_origem,
                            ie_oncologia,
                            ie_urgencia,
                            qt_dias_padrao,
                            dt_inicio,
                            cd_recomendacao,
                            dt_liberacao,
                            nr_seq_pepo,
                            dt_lib_suspensao,
                            ie_nivel_atencao,
                            dt_prox_geracao,
                            ie_retrogrado,
                            dt_liberacao_enf,
                            ie_item_valido,
                            cd_medico,
                            nr_cirurgia,
                            ie_administracao,
                            dt_atualizacao_nrec,
                            nr_seq_transcricao,
                            ie_prescritor_aux,
                            nr_sequencia,
                            dt_liberacao_aux,
                            ie_futuro,
                            dt_liberacao_farm,
                            dt_ciencia_medico,
                            ie_acm,
                            ie_periodo,
                            ie_duracao,
                            nr_ocorrencia,
                            hr_prim_horario,
                            cd_pessoa_fisica,
                            nr_cirurgia_patologia,
                            cd_perfil_ativo,
                            ie_se_necessario,
                            ds_recomendacao,
                            dt_atualizacao,
                            cd_intervalo,
                            ie_item_alta,
                            nr_seq_topografia,
                            ie_evento_unico,
                            nr_seq_soap,
                            nm_usuario,
                            nr_seq_cpoe_anterior,
                            dt_fim,
                            nr_seq_agenda,
                            nr_atendimento,
                            ie_tipo_prescr_cirur,
                            ds_justificativa,
                            nr_seq_conclusao_apae,
                            nm_usuario_nrec,
                            ds_horarios,
                            cd_setor_atendimento
                        ) VALUES (
                            2314,
                           'N',
                            NULL,
                            NULL,
                            DT_LIBERACAO_W,
                            325,
                            NULL,
                            NULL,
                            NULL,
                            'T',
                            NULL,
                            'N',
                            NULL,
                            'S',
                            NULL,
                            NULL,
                            'P',
                            DT_ATT_W,
                            NULL,
                            NULL,
                            NR_SEQ_W,
                            NULL,
                            'N',
                            NULL,
                            NULL,
                            'N',
                            NULL,
                            'C',
                            1.0,
                            TO_CHAR(DT_ATT_W,'HH24:MI'),
                            CD_PESSOA_FISICA_W,
                            NULL,
                            NULL,
                            'S',
                            NULL,
                            DT_ATT_W,
                            'Cont',
                            'N',
                            NULL,
                            'N',
                            NULL,
                            obter_usuario_ativo(),
                            NULL,
                            NULL,
                            NULL,
                            nr_atendimento_w,
                            NULL,
                            NULL,
                            NULL,
                            obter_usuario_ativo(),
                            NULL,
                            NULL
                        );
                        
                        IE_VERIFICA_REC := IE_VERIFICA_REC + 1;
                END IF;
                
                IF(nr_seq_precaucao_w = 8 AND  IE_VERIFICA_REC = 0) -- Goticulas
                THEN
                            NR_SEQ_W := cpoe_recomendacao_seq.NEXTVAL;
                
                            INSERT INTO cpoe_recomendacao (
                            cd_funcao_origem,
                            ie_oncologia,
                            ie_urgencia,
                            qt_dias_padrao,
                            dt_inicio,
                            cd_recomendacao,
                            dt_liberacao,
                            nr_seq_pepo,
                            dt_lib_suspensao,
                            ie_nivel_atencao,
                            dt_prox_geracao,
                            ie_retrogrado,
                            dt_liberacao_enf,
                            ie_item_valido,
                            cd_medico,
                            nr_cirurgia,
                            ie_administracao,
                            dt_atualizacao_nrec,
                            nr_seq_transcricao,
                            ie_prescritor_aux,
                            nr_sequencia,
                            dt_liberacao_aux,
                            ie_futuro,
                            dt_liberacao_farm,
                            dt_ciencia_medico,
                            ie_acm,
                            ie_periodo,
                            ie_duracao,
                            nr_ocorrencia,
                            hr_prim_horario,
                            cd_pessoa_fisica,
                            nr_cirurgia_patologia,
                            cd_perfil_ativo,
                            ie_se_necessario,
                            ds_recomendacao,
                            dt_atualizacao,
                            cd_intervalo,
                            ie_item_alta,
                            nr_seq_topografia,
                            ie_evento_unico,
                            nr_seq_soap,
                            nm_usuario,
                            nr_seq_cpoe_anterior,
                            dt_fim,
                            nr_seq_agenda,
                            nr_atendimento,
                            ie_tipo_prescr_cirur,
                            ds_justificativa,
                            nr_seq_conclusao_apae,
                            nm_usuario_nrec,
                            ds_horarios,
                            cd_setor_atendimento
                        ) VALUES (
                            2314,
                           'N',
                            NULL,
                            NULL,
                            DT_LIBERACAO_W,
                            326,
                            NULL,
                            NULL,
                            NULL,
                            'T',
                            NULL,
                            'N',
                            NULL,
                            'S',
                            NULL,
                            NULL,
                            'P',
                            DT_ATT_W,
                            NULL,
                            NULL,
                            NR_SEQ_W,
                            NULL,
                            'N',
                            NULL,
                            NULL,
                            'N',
                            NULL,
                            'C',
                            1.0,
                            TO_CHAR(DT_ATT_W,'HH24:MI'),
                            CD_PESSOA_FISICA_W,
                            NULL,
                            NULL,
                            'S',
                            NULL,
                            DT_ATT_W,
                            'Cont',
                            'N',
                            NULL,
                            'N',
                            NULL,
                            obter_usuario_ativo(),
                            NULL,
                            NULL,
                            NULL,
                            nr_atendimento_w,
                            NULL,
                            NULL,
                            NULL,
                            obter_usuario_ativo(),
                            NULL,
                            NULL
                        );
                        
                        IE_VERIFICA_REC := IE_VERIFICA_REC + 1;
                END IF;
            
        
        
    END IF;

END HCD_TRG_GERA_RECOM_PRECAUCAO;