CREATE OR REPLACE TRIGGER HCD_EXECUTOR_ORDEM_SERVICO
BEFORE INSERT ON MAN_ORDEM_SERVICO_EXEC
FOR EACH ROW

/*<DS_SCRIPT>
 DESCRIÇÃO...: TRIGGER QUE AUTOMATIZA A INFORMAÇÃO DO USUÁRIO EXECUTANTE CONFORME É INFORMADO NA ABA EXECUTOR PREVISTO
 RESPONSAVEL.: DOUGLAS FELIPE 
 DATA........: 05/10/2022
 APLICAÇÃO...: TASY - Gestão de Ordem de Serviço
 ATUALIZAÇÃO...:

</DS_SCRIPT>*/

DECLARE

NM_USUARIO_EXEC_W VARCHAR2(255) := :NEW.NM_USUARIO_EXEC;
NM_USUARIO_W VARCHAR2(255) := :NEW.NM_USUARIO;
NR_SEQ_ORDEM_W NUMBER (10,0) :=  :NEW.NR_SEQ_ORDEM;

BEGIN

HCD_MAN_DEFINIR_USUARIO_EXEC(NR_SEQ_ORDEM_W,NM_USUARIO_EXEC_W,NM_USUARIO_W,2);

UPDATE MAN_ORDEM_SERVICO 
SET IE_STATUS_ORDEM = 2, DT_INICIO_REAL = SYSDATE 
WHERE NR_SEQUENCIA = NR_SEQ_ORDEM_W;

END HCD_EXECUTOR_ORDEM_SERVICO;
