create or replace TRIGGER SIM_ADC_ASS_ATESTADO_CPOE
AFTER INSERT ON SIM_LOG_CPOE_ATESTADO
FOR EACH ROW

--<DS_SCRIPT>
-- DESCRIÇÃO..............: Leva a assinatura digital da CPOE para o item de prontuário ATESTADO
-- RESPONSAVEL............: DOUGLAS FELIPE / ANDERSON FARIAS
-- DATA...................: 27/06/2022
-- APLICAÇÃO..............: TASY <CPOE>
--</DS_SCRIPT>

DECLARE
CD_MEDICO_W NUMBER := :NEW.CD_MEDICO;
NR_SEQ_ATESTADO_W NUMBER := :NEW.NR_SEQ_ATESTADO;
DT_ATUALIZACAO_W DATE := :NEW.DT_ATUALIZACAO;

NR_SEQ_ASSINATURA_W NUMBER;

BEGIN


    -- PEGA A ASSINATURA DESTA PRESCRIÇÃO --
    
    select MAX(NR_SEQUENCIA) INTO NR_SEQ_ASSINATURA_W from tasy_assinatura_digital WHERE nr_seq_proj_ass = 53355 
    AND TO_CHAR(DT_REGISTRO, 'DD/MM/YYYY HH24:MI') = TO_CHAR(DT_ATUALIZACAO, 'DD/MM/YYYY HH24:MI')
    AND CD_PESSOA_FISICA = CD_MEDICO_W;

    UPDATE ATESTADO_PACIENTE SET NR_SEQ_ASSINATURA = NR_SEQ_ASSINATURA_W WHERE NR_SEQUENCIA = NR_SEQ_ATESTADO_W;

END SIM_ADC_ASS_ATESTADO_CPOE;