create or replace PROCEDURE AGINT_ALTERAR_TIPO_ORCAMENTO (NR_SEQUENCIA_ORCAMENTO_P IN NUMBER)

/*<DS_SCRIPT>
 DESCRIÇÃO...: PROCEDURE QUE ALTERA O TIPO DE ORÇAMENTO PARA "TEM INTERESSE/PESQUISA PREÇO"  AO MESMO SER ENVIADO AO PACIENTE (PLATAFORMA AGENDA INTEGRADA)
 RESPONSAVEL.: DOUGLAS FELIPE (douglas.fs)
 DATA........: 24/12/2021
 APLICAÇÃO...: Ageda Integrada
</DS_SCRIPT>
<USUARIO=TASY>*/

IS
        DS_RETORNO_W NUMBER;
BEGIN

    SELECT IE_STATUS_ORCAMENTO INTO DS_RETORNO_W
    FROM ORCAMENTO_PACIENTE WHERE NR_SEQUENCIA_ORCAMENTO = NR_SEQUENCIA_ORCAMENTO_P;

    IF (DS_RETORNO_W <> 11) 
    THEN UPDATE ORCAMENTO_PACIENTE SET IE_STATUS_ORCAMENTO = 11 WHERE NR_SEQUENCIA_ORCAMENTO = NR_SEQUENCIA_ORCAMENTO_P; 
    END IF;


END AGINT_ALTERAR_TIPO_ORCAMENTO;